package com.taikesoft.itsm.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOpPlan<M extends BaseOpPlan<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setPlanDate(java.util.Date planDate) {
		set("plan_date", planDate);
	}
	
	public java.util.Date getPlanDate() {
		return get("plan_date");
	}

	public void setOrgId(java.lang.String orgId) {
		set("org_id", orgId);
	}
	
	public java.lang.String getOrgId() {
		return getStr("org_id");
	}

	public void setStcd(java.lang.String stcd) {
		set("stcd", stcd);
	}
	
	public java.lang.String getStcd() {
		return getStr("stcd");
	}

	public void setPlanType(java.lang.String planType) {
		set("plan_type", planType);
	}
	
	public java.lang.String getPlanType() {
		return getStr("plan_type");
	}

	public void setMemo(java.lang.String memo) {
		set("memo", memo);
	}
	
	public java.lang.String getMemo() {
		return getStr("memo");
	}

	public void setUserId(java.lang.Integer userId) {
		set("user_id", userId);
	}
	
	public java.lang.Integer getUserId() {
		return getInt("user_id");
	}

	public void setUsername(java.lang.String username) {
		set("username", username);
	}
	
	public java.lang.String getUsername() {
		return getStr("username");
	}

	public void setIsvalid(java.lang.String isvalid) {
		set("isvalid", isvalid);
	}
	
	public java.lang.String getIsvalid() {
		return getStr("isvalid");
	}

	public void setCreateBy(java.lang.Integer createBy) {
		set("create_by", createBy);
	}
	
	public java.lang.Integer getCreateBy() {
		return getInt("create_by");
	}

	public void setCreateName(java.lang.String createName) {
		set("create_name", createName);
	}
	
	public java.lang.String getCreateName() {
		return getStr("create_name");
	}

	public void setCreateAt(java.util.Date createAt) {
		set("create_at", createAt);
	}
	
	public java.util.Date getCreateAt() {
		return get("create_at");
	}

	public void setUpdateBy(java.lang.Integer updateBy) {
		set("update_by", updateBy);
	}
	
	public java.lang.Integer getUpdateBy() {
		return getInt("update_by");
	}

	public void setUpdateName(java.lang.String updateName) {
		set("update_name", updateName);
	}
	
	public java.lang.String getUpdateName() {
		return getStr("update_name");
	}

	public void setUpdateAt(java.util.Date updateAt) {
		set("update_at", updateAt);
	}
	
	public java.util.Date getUpdateAt() {
		return get("update_at");
	}

	public void setExecuteDate(java.util.Date executeDate) {
		set("execute_date", executeDate);
	}
	
	public java.util.Date getExecuteDate() {
		return get("execute_date");
	}

	public void setExecuted(java.lang.String executed) {
		set("executed", executed);
	}
	
	public java.lang.String getExecuted() {
		return getStr("executed");
	}

	public void setIncidentId(java.lang.String incidentId) {
		set("incidentId", incidentId);
	}
	
	public java.lang.String getIncidentId() {
		return getStr("incidentId");
	}

}
