package com.taikesoft.itsm.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStStppB<M extends BaseStStppB<M>> extends Model<M> implements IBean {

	public void setRowguid(java.lang.String rowguid) {
		set("rowguid", rowguid);
	}
	
	public java.lang.String getRowguid() {
		return getStr("rowguid");
	}

	public void setIsvalid(java.lang.String isvalid) {
		set("isvalid", isvalid);
	}
	
	public java.lang.String getIsvalid() {
		return getStr("isvalid");
	}

	public void setStgd(java.lang.String stgd) {
		set("stgd", stgd);
	}
	
	public java.lang.String getStgd() {
		return getStr("stgd");
	}

	public void setPpnum(java.lang.Integer ppnum) {
		set("ppnum", ppnum);
	}
	
	public java.lang.Integer getPpnum() {
		return getInt("ppnum");
	}

	public void setPpnm(java.lang.String ppnm) {
		set("ppnm", ppnm);
	}
	
	public java.lang.String getPpnm() {
		return getStr("ppnm");
	}

	public void setPpmd(java.lang.String ppmd) {
		set("ppmd", ppmd);
	}
	
	public java.lang.String getPpmd() {
		return getStr("ppmd");
	}

	public void setPpf(java.math.BigDecimal ppf) {
		set("ppf", ppf);
	}
	
	public java.math.BigDecimal getPpf() {
		return get("ppf");
	}

	public void setPppw(java.lang.Integer pppw) {
		set("pppw", pppw);
	}
	
	public java.lang.Integer getPppw() {
		return getInt("pppw");
	}

	public void setPptp(java.lang.String pptp) {
		set("pptp", pptp);
	}
	
	public java.lang.String getPptp() {
		return getStr("pptp");
	}

	public void setPppsfl(java.lang.String pppsfl) {
		set("pppsfl", pppsfl);
	}
	
	public java.lang.String getPppsfl() {
		return getStr("pppsfl");
	}

	public void setPpscramfl(java.lang.String ppscramfl) {
		set("ppscramfl", ppscramfl);
	}
	
	public java.lang.String getPpscramfl() {
		return getStr("ppscramfl");
	}

	public void setPpssffl(java.lang.String ppssffl) {
		set("ppssffl", ppssffl);
	}
	
	public java.lang.String getPpssffl() {
		return getStr("ppssffl");
	}

	public void setPprt(java.lang.String pprt) {
		set("pprt", pprt);
	}
	
	public java.lang.String getPprt() {
		return getStr("pprt");
	}

	public void setComments(java.lang.String comments) {
		set("comments", comments);
	}
	
	public java.lang.String getComments() {
		return getStr("comments");
	}

}
