package com.taikesoft.itsm.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStStgtB<M extends BaseStStgtB<M>> extends Model<M> implements IBean {

	public void setRowguid(java.lang.String rowguid) {
		set("rowguid", rowguid);
	}
	
	public java.lang.String getRowguid() {
		return getStr("rowguid");
	}

	public void setIsvalid(java.lang.String isvalid) {
		set("isvalid", isvalid);
	}
	
	public java.lang.String getIsvalid() {
		return getStr("isvalid");
	}

	public void setStgd(java.lang.String stgd) {
		set("stgd", stgd);
	}
	
	public java.lang.String getStgd() {
		return getStr("stgd");
	}

	public void setGtnum(java.lang.Integer gtnum) {
		set("gtnum", gtnum);
	}
	
	public java.lang.Integer getGtnum() {
		return getInt("gtnum");
	}

	public void setGtnm(java.lang.String gtnm) {
		set("gtnm", gtnm);
	}
	
	public java.lang.String getGtnm() {
		return getStr("gtnm");
	}

	public void setGttp(java.lang.String gttp) {
		set("gttp", gttp);
	}
	
	public java.lang.String getGttp() {
		return getStr("gttp");
	}

	public void setGtw(java.math.BigDecimal gtw) {
		set("gtw", gtw);
	}
	
	public java.math.BigDecimal getGtw() {
		return get("gtw");
	}

	public void setGth(java.math.BigDecimal gth) {
		set("gth", gth);
	}
	
	public java.math.BigDecimal getGth() {
		return get("gth");
	}

	public void setGtf(java.math.BigDecimal gtf) {
		set("gtf", gtf);
	}
	
	public java.math.BigDecimal getGtf() {
		return get("gtf");
	}

	public void setGtrt(java.lang.String gtrt) {
		set("gtrt", gtrt);
	}
	
	public java.lang.String getGtrt() {
		return getStr("gtrt");
	}

	public void setGtpsfl(java.lang.String gtpsfl) {
		set("gtpsfl", gtpsfl);
	}
	
	public java.lang.String getGtpsfl() {
		return getStr("gtpsfl");
	}

	public void setComments(java.lang.String comments) {
		set("comments", comments);
	}
	
	public java.lang.String getComments() {
		return getStr("comments");
	}

}
