package com.taikesoft.itsm.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStRainfullI<M extends BaseStRainfullI<M>> extends Model<M> implements IBean {

	public void setRowguid(java.lang.String rowguid) {
		set("rowguid", rowguid);
	}
	
	public java.lang.String getRowguid() {
		return getStr("rowguid");
	}

	public void setIsvalid(java.lang.String isvalid) {
		set("isvalid", isvalid);
	}
	
	public java.lang.String getIsvalid() {
		return getStr("isvalid");
	}

	public void setStgd(java.lang.String stgd) {
		set("stgd", stgd);
	}
	
	public java.lang.String getStgd() {
		return getStr("stgd");
	}

	public void setTm(java.util.Date tm) {
		set("tm", tm);
	}
	
	public java.util.Date getTm() {
		return get("tm");
	}

	public void setPtm(java.util.Date ptm) {
		set("ptm", ptm);
	}
	
	public java.util.Date getPtm() {
		return get("ptm");
	}

	public void setDyp(java.math.BigDecimal dyp) {
		set("dyp", dyp);
	}
	
	public java.math.BigDecimal getDyp() {
		return get("dyp");
	}

}
