package com.taikesoft.itsm.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStStszB<M extends BaseStStszB<M>> extends Model<M> implements IBean {

	public void setRowguid(java.lang.String rowguid) {
		set("rowguid", rowguid);
	}
	
	public java.lang.String getRowguid() {
		return getStr("rowguid");
	}

	public void setIsvalid(java.lang.String isvalid) {
		set("isvalid", isvalid);
	}
	
	public java.lang.String getIsvalid() {
		return getStr("isvalid");
	}

	public void setStgd(java.lang.String stgd) {
		set("stgd", stgd);
	}
	
	public java.lang.String getStgd() {
		return getStr("stgd");
	}

	public void setUpstgd(java.lang.String upstgd) {
		set("upstgd", upstgd);
	}
	
	public java.lang.String getUpstgd() {
		return getStr("upstgd");
	}

	public void setUptp(java.lang.String uptp) {
		set("uptp", uptp);
	}
	
	public java.lang.String getUptp() {
		return getStr("uptp");
	}

	public void setDwstgd(java.lang.String dwstgd) {
		set("dwstgd", dwstgd);
	}
	
	public java.lang.String getDwstgd() {
		return getStr("dwstgd");
	}

	public void setDwtp(java.lang.String dwtp) {
		set("dwtp", dwtp);
	}
	
	public java.lang.String getDwtp() {
		return getStr("dwtp");
	}

	public void setUph(java.math.BigDecimal uph) {
		set("uph", uph);
	}
	
	public java.math.BigDecimal getUph() {
		return get("uph");
	}

	public void setUpl(java.math.BigDecimal upl) {
		set("upl", upl);
	}
	
	public java.math.BigDecimal getUpl() {
		return get("upl");
	}

	public void setDwh(java.math.BigDecimal dwh) {
		set("dwh", dwh);
	}
	
	public java.math.BigDecimal getDwh() {
		return get("dwh");
	}

	public void setDwl(java.math.BigDecimal dwl) {
		set("dwl", dwl);
	}
	
	public java.math.BigDecimal getDwl() {
		return get("dwl");
	}

	public void setUpsh(java.math.BigDecimal upsh) {
		set("upsh", upsh);
	}
	
	public java.math.BigDecimal getUpsh() {
		return get("upsh");
	}

	public void setUpsl(java.math.BigDecimal upsl) {
		set("upsl", upsl);
	}
	
	public java.math.BigDecimal getUpsl() {
		return get("upsl");
	}

	public void setDwsh(java.math.BigDecimal dwsh) {
		set("dwsh", dwsh);
	}
	
	public java.math.BigDecimal getDwsh() {
		return get("dwsh");
	}

	public void setDwsl(java.math.BigDecimal dwsl) {
		set("dwsl", dwsl);
	}
	
	public java.math.BigDecimal getDwsl() {
		return get("dwsl");
	}

	public void setRh(java.math.BigDecimal rh) {
		set("rh", rh);
	}
	
	public java.math.BigDecimal getRh() {
		return get("rh");
	}

}
