package com.taikesoft.itsm.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStWaterChangeI<M extends BaseStWaterChangeI<M>> extends Model<M> implements IBean {

	public void setRowguid(java.lang.String rowguid) {
		set("rowguid", rowguid);
	}
	
	public java.lang.String getRowguid() {
		return getStr("rowguid");
	}

	public void setIsvalid(java.lang.String isvalid) {
		set("isvalid", isvalid);
	}
	
	public java.lang.String getIsvalid() {
		return getStr("isvalid");
	}

	public void setStgd(java.lang.String stgd) {
		set("stgd", stgd);
	}
	
	public java.lang.String getStgd() {
		return getStr("stgd");
	}

	public void setTm(java.util.Date tm) {
		set("tm", tm);
	}
	
	public java.util.Date getTm() {
		return get("tm");
	}

	public void setUph(java.math.BigDecimal uph) {
		set("uph", uph);
	}
	
	public java.math.BigDecimal getUph() {
		return get("uph");
	}

	public void setUphtm(java.util.Date uphtm) {
		set("uphtm", uphtm);
	}
	
	public java.util.Date getUphtm() {
		return get("uphtm");
	}

	public void setUpl(java.math.BigDecimal upl) {
		set("upl", upl);
	}
	
	public java.math.BigDecimal getUpl() {
		return get("upl");
	}

	public void setUpltm(java.util.Date upltm) {
		set("upltm", upltm);
	}
	
	public java.util.Date getUpltm() {
		return get("upltm");
	}

	public void setUpdiff(java.math.BigDecimal updiff) {
		set("updiff", updiff);
	}
	
	public java.math.BigDecimal getUpdiff() {
		return get("updiff");
	}

	public void setDwh(java.math.BigDecimal dwh) {
		set("dwh", dwh);
	}
	
	public java.math.BigDecimal getDwh() {
		return get("dwh");
	}

	public void setDwhtm(java.util.Date dwhtm) {
		set("dwhtm", dwhtm);
	}
	
	public java.util.Date getDwhtm() {
		return get("dwhtm");
	}

	public void setDwl(java.math.BigDecimal dwl) {
		set("dwl", dwl);
	}
	
	public java.math.BigDecimal getDwl() {
		return get("dwl");
	}

	public void setDwltm(java.util.Date dwltm) {
		set("dwltm", dwltm);
	}
	
	public java.util.Date getDwltm() {
		return get("dwltm");
	}

	public void setDwdiff(java.math.BigDecimal dwdiff) {
		set("dwdiff", dwdiff);
	}
	
	public java.math.BigDecimal getDwdiff() {
		return get("dwdiff");
	}

}
