package com.taikesoft.itsm.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOpOtherLog<M extends BaseOpOtherLog<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setPlanId(java.lang.String planId) {
		set("plan_id", planId);
	}
	
	public java.lang.String getPlanId() {
		return getStr("plan_id");
	}

	public void setExecuteDesc(java.lang.String executeDesc) {
		set("execute_desc", executeDesc);
	}
	
	public java.lang.String getExecuteDesc() {
		return getStr("execute_desc");
	}

	public void setCreateBy(java.lang.Integer createBy) {
		set("create_by", createBy);
	}
	
	public java.lang.Integer getCreateBy() {
		return getInt("create_by");
	}

	public void setCreateName(java.lang.String createName) {
		set("create_name", createName);
	}
	
	public java.lang.String getCreateName() {
		return getStr("create_name");
	}

	public void setCreateAt(java.util.Date createAt) {
		set("create_at", createAt);
	}
	
	public java.util.Date getCreateAt() {
		return get("create_at");
	}

}
