package com.taikesoft.itsm.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOpIncident<M extends BaseOpIncident<M>> extends Model<M> implements IBean {

	public void setRowguid(java.lang.String rowguid) {
		set("rowguid", rowguid);
	}
	
	public java.lang.String getRowguid() {
		return getStr("rowguid");
	}

	public void setOrgid(java.lang.String orgid) {
		set("orgid", orgid);
	}
	
	public java.lang.String getOrgid() {
		return getStr("orgid");
	}

	public void setStcd(java.lang.String stcd) {
		set("stcd", stcd);
	}
	
	public java.lang.String getStcd() {
		return getStr("stcd");
	}

	public java.lang.String getPlanId() {
		return getStr("planId");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}
	
	public java.lang.String getTitle() {
		return getStr("title");
	}

	public void setUrgency(java.lang.String urgency) {
		set("urgency", urgency);
	}
	
	public java.lang.String getUrgency() {
		return getStr("urgency");
	}

	public void setOrigin(java.lang.String origin) {
		set("origin", origin);
	}
	
	public java.lang.String getOrigin() {
		return getStr("origin");
	}

	public void setSolution(java.lang.String solution) {
		set("solution", solution);
	}
	
	public java.lang.String getSolution() {
		return getStr("solution");
	}

	public void setSolveDate(java.util.Date solveDate) {
		set("solveDate", solveDate);
	}
	
	public java.util.Date getSolveDate() {
		return get("solveDate");
	}

	public void setEndDate(java.util.Date endDate) {
		set("endDate", endDate);
	}
	
	public java.util.Date getEndDate() {
		return get("endDate");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public void setIsValid(java.lang.Integer isValid) {
		set("isValid", isValid);
	}
	
	public java.lang.Integer getIsValid() {
		return getInt("isValid");
	}

	public void setCreateId(java.lang.Integer createId) {
		set("createId", createId);
	}
	
	public java.lang.Integer getCreateId() {
		return getInt("createId");
	}

	public void setCreateName(java.lang.String createName) {
		set("createName", createName);
	}
	
	public java.lang.String getCreateName() {
		return getStr("createName");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setUpdateId(java.lang.Integer updateId) {
		set("updateId", updateId);
	}
	
	public java.lang.Integer getUpdateId() {
		return getInt("updateId");
	}

	public void setUpdateName(java.lang.String updateName) {
		set("updateName", updateName);
	}
	
	public java.lang.String getUpdateName() {
		return getStr("updateName");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}
	
	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

}
