package com.taikesoft.itsm.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStVideoAbnormalI<M extends BaseStVideoAbnormalI<M>> extends Model<M> implements IBean {

	public void setRowguid(java.lang.String rowguid) {
		set("rowguid", rowguid);
	}
	
	public java.lang.String getRowguid() {
		return getStr("rowguid");
	}

	public void setIsvalid(java.lang.String isvalid) {
		set("isvalid", isvalid);
	}
	
	public java.lang.String getIsvalid() {
		return getStr("isvalid");
	}

	public void setIpcgd(java.lang.String ipcgd) {
		set("ipcgd", ipcgd);
	}
	
	public java.lang.String getIpcgd() {
		return getStr("ipcgd");
	}

	public void setTm(java.util.Date tm) {
		set("tm", tm);
	}
	
	public java.util.Date getTm() {
		return get("tm");
	}

	public void setErrorcd(java.lang.Integer errorcd) {
		set("errorcd", errorcd);
	}
	
	public java.lang.Integer getErrorcd() {
		return getInt("errorcd");
	}

}
