package com.taikesoft.itsm.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysAccount<M extends BaseSysAccount<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setUsername(java.lang.String username) {
		set("username", username);
	}
	
	public java.lang.String getUsername() {
		return getStr("username");
	}

	public void setPassword(java.lang.String password) {
		set("password", password);
	}
	
	public java.lang.String getPassword() {
		return getStr("password");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public void setGender(java.lang.String gender) {
		set("gender", gender);
	}
	
	public java.lang.String getGender() {
		return getStr("gender");
	}

	public void setPhone(java.lang.String phone) {
		set("phone", phone);
	}
	
	public java.lang.String getPhone() {
		return getStr("phone");
	}

	public void setEmail(java.lang.String email) {
		set("email", email);
	}
	
	public java.lang.String getEmail() {
		return getStr("email");
	}

	public void setDescription(java.lang.String description) {
		set("description", description);
	}
	
	public java.lang.String getDescription() {
		return getStr("description");
	}

	public void setWxid(java.lang.String wxid) {
		set("wxid", wxid);
	}
	
	public java.lang.String getWxid() {
		return getStr("wxid");
	}

	public void setQuitAt(java.util.Date quitAt) {
		set("quit_at", quitAt);
	}
	
	public java.util.Date getQuitAt() {
		return get("quit_at");
	}

	public void setLoginIp(java.lang.String loginIp) {
		set("login_ip", loginIp);
	}
	
	public java.lang.String getLoginIp() {
		return getStr("login_ip");
	}

	public void setLoginAt(java.util.Date loginAt) {
		set("login_at", loginAt);
	}
	
	public java.util.Date getLoginAt() {
		return get("login_at");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public void setSortNumber(java.lang.Integer sortNumber) {
		set("sort_number", sortNumber);
	}
	
	public java.lang.Integer getSortNumber() {
		return getInt("sort_number");
	}

}
