package com.taikesoft.itsm.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStVcrB<M extends BaseStVcrB<M>> extends Model<M> implements IBean {

	public void setRowguid(java.lang.String rowguid) {
		set("rowguid", rowguid);
	}
	
	public java.lang.String getRowguid() {
		return getStr("rowguid");
	}

	public void setIsvalid(java.lang.String isvalid) {
		set("isvalid", isvalid);
	}
	
	public java.lang.String getIsvalid() {
		return getStr("isvalid");
	}

	public void setInstgd(java.lang.String instgd) {
		set("instgd", instgd);
	}
	
	public java.lang.String getInstgd() {
		return getStr("instgd");
	}

	public void setLid(java.lang.String lid) {
		set("lid", lid);
	}
	
	public java.lang.String getLid() {
		return getStr("lid");
	}

	public void setLpwd(java.lang.String lpwd) {
		set("lpwd", lpwd);
	}
	
	public java.lang.String getLpwd() {
		return getStr("lpwd");
	}

	public void setAcnum(java.lang.Integer acnum) {
		set("acnum", acnum);
	}
	
	public java.lang.Integer getAcnum() {
		return getInt("acnum");
	}

	public void setDcnum(java.lang.Integer dcnum) {
		set("dcnum", dcnum);
	}
	
	public java.lang.Integer getDcnum() {
		return getInt("dcnum");
	}

	public void setZcnum(java.lang.Integer zcnum) {
		set("zcnum", zcnum);
	}
	
	public java.lang.Integer getZcnum() {
		return getInt("zcnum");
	}

	public void setInnerip(java.lang.String innerip) {
		set("innerip", innerip);
	}
	
	public java.lang.String getInnerip() {
		return getStr("innerip");
	}

	public void setInnerport(java.lang.String innerport) {
		set("innerport", innerport);
	}
	
	public java.lang.String getInnerport() {
		return getStr("innerport");
	}

	public void setInnersp(java.lang.String innersp) {
		set("innersp", innersp);
	}
	
	public java.lang.String getInnersp() {
		return getStr("innersp");
	}

	public void setOuterip(java.lang.String outerip) {
		set("outerip", outerip);
	}
	
	public java.lang.String getOuterip() {
		return getStr("outerip");
	}

	public void setOuyerport(java.lang.String ouyerport) {
		set("ouyerport", ouyerport);
	}
	
	public java.lang.String getOuyerport() {
		return getStr("ouyerport");
	}

	public void setOutersp(java.lang.String outersp) {
		set("outersp", outersp);
	}
	
	public java.lang.String getOutersp() {
		return getStr("outersp");
	}

	public void setComments(java.lang.String comments) {
		set("comments", comments);
	}
	
	public java.lang.String getComments() {
		return getStr("comments");
	}

}
