package com.taikesoft.itsm.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStStbprpB<M extends BaseStStbprpB<M>> extends Model<M> implements IBean {

	public void setRowguid(java.lang.String rowguid) {
		set("rowguid", rowguid);
	}
	
	public java.lang.String getRowguid() {
		return getStr("rowguid");
	}

	public void setIsvalid(java.lang.String isvalid) {
		set("isvalid", isvalid);
	}
	
	public java.lang.String getIsvalid() {
		return getStr("isvalid");
	}

	public void setStnm(java.lang.String stnm) {
		set("stnm", stnm);
	}
	
	public java.lang.String getStnm() {
		return getStr("stnm");
	}

	public void setInstgd(java.lang.String instgd) {
		set("instgd", instgd);
	}
	
	public java.lang.String getInstgd() {
		return getStr("instgd");
	}

	public void setStcd(java.lang.String stcd) {
		set("stcd", stcd);
	}
	
	public java.lang.String getStcd() {
		return getStr("stcd");
	}

	public void setSttype(java.lang.String sttype) {
		set("sttype", sttype);
	}
	
	public java.lang.String getSttype() {
		return getStr("sttype");
	}

	public void setLgtd(java.math.BigDecimal lgtd) {
		set("lgtd", lgtd);
	}
	
	public java.math.BigDecimal getLgtd() {
		return get("lgtd");
	}

	public void setLttd(java.math.BigDecimal lttd) {
		set("lttd", lttd);
	}
	
	public java.math.BigDecimal getLttd() {
		return get("lttd");
	}

	public void setKeeper(java.lang.String keeper) {
		set("keeper", keeper);
	}
	
	public java.lang.String getKeeper() {
		return getStr("keeper");
	}

	public void setKeepercontact(java.lang.String keepercontact) {
		set("keepercontact", keepercontact);
	}
	
	public java.lang.String getKeepercontact() {
		return getStr("keepercontact");
	}

	public void setVcrnum(java.lang.Integer vcrnum) {
		set("vcrnum", vcrnum);
	}
	
	public java.lang.Integer getVcrnum() {
		return getInt("vcrnum");
	}

	public void setPpnum(java.lang.Integer ppnum) {
		set("ppnum", ppnum);
	}
	
	public java.lang.Integer getPpnum() {
		return getInt("ppnum");
	}

	public void setGtnum(java.lang.Integer gtnum) {
		set("gtnum", gtnum);
	}
	
	public java.lang.Integer getGtnum() {
		return getInt("gtnum");
	}

	public void setUpzfl(java.lang.String upzfl) {
		set("upzfl", upzfl);
	}
	
	public java.lang.String getUpzfl() {
		return getStr("upzfl");
	}

	public void setDwzfl(java.lang.String dwzfl) {
		set("dwzfl", dwzfl);
	}
	
	public java.lang.String getDwzfl() {
		return getStr("dwzfl");
	}

	public void setPfl(java.lang.String pfl) {
		set("pfl", pfl);
	}
	
	public java.lang.String getPfl() {
		return getStr("pfl");
	}

	public void setSortnum(java.lang.Integer sortnum) {
		set("sortnum", sortnum);
	}
	
	public java.lang.Integer getSortnum() {
		return getInt("sortnum");
	}

	public void setComments(java.lang.String comments) {
		set("comments", comments);
	}
	
	public java.lang.String getComments() {
		return getStr("comments");
	}

}
