package com.taikesoft.itsm.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOpAttachment<M extends BaseOpAttachment<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public void setType(java.lang.String type) {
		set("type", type);
	}
	
	public java.lang.String getType() {
		return getStr("type");
	}

	public void setPath(java.lang.String path) {
		set("path", path);
	}
	
	public java.lang.String getPath() {
		return getStr("path");
	}

	public void setTableName(java.lang.String tableName) {
		set("table_name", tableName);
	}
	
	public java.lang.String getTableName() {
		return getStr("table_name");
	}

	public void setBid(java.lang.String bid) {
		set("bid", bid);
	}
	
	public java.lang.String getBid() {
		return getStr("bid");
	}

	public void setMemo(java.lang.String memo) {
		set("memo", memo);
	}
	
	public java.lang.String getMemo() {
		return getStr("memo");
	}

	public void setSortNumber(java.lang.Integer sortNumber) {
		set("sort_number", sortNumber);
	}
	
	public java.lang.Integer getSortNumber() {
		return getInt("sort_number");
	}

	public void setIsvalid(java.lang.String isvalid) {
		set("isvalid", isvalid);
	}
	
	public java.lang.String getIsvalid() {
		return getStr("isvalid");
	}

	public void setCreateBy(java.lang.Integer createBy) {
		set("create_by", createBy);
	}
	
	public java.lang.Integer getCreateBy() {
		return getInt("create_by");
	}

	public void setCreateName(java.lang.String createName) {
		set("create_name", createName);
	}
	
	public java.lang.String getCreateName() {
		return getStr("create_name");
	}

	public void setCreateAt(java.util.Date createAt) {
		set("create_at", createAt);
	}
	
	public java.util.Date getCreateAt() {
		return get("create_at");
	}

	public void setUpdateBy(java.lang.Integer updateBy) {
		set("update_by", updateBy);
	}
	
	public java.lang.Integer getUpdateBy() {
		return getInt("update_by");
	}

	public void setUpdateName(java.lang.String updateName) {
		set("update_name", updateName);
	}
	
	public java.lang.String getUpdateName() {
		return getStr("update_name");
	}

	public void setUpdateAt(java.util.Date updateAt) {
		set("update_at", updateAt);
	}
	
	public java.util.Date getUpdateAt() {
		return get("update_at");
	}

}
