package com.taikesoft.itsm.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("op_attachment", "id", OpAttachment.class);
		arp.addMapping("op_content", "id", OpContent.class);
		arp.addMapping("op_incident", "rowguid", OpIncident.class);
		arp.addMapping("op_inspect_log", "id", OpInspectLog.class);
		arp.addMapping("op_other_log", "id", OpOtherLog.class);
		arp.addMapping("op_plan", "id", OpPlan.class);
		arp.addMapping("op_repair_log", "id", OpRepairLog.class);
		arp.addMapping("st_instcd_b", "rowguid", StInstcdB.class);
		arp.addMapping("st_ipc_b", "rowguid", StIpcB.class);
		arp.addMapping("st_lastwater_s", "rowguid", StLastwaterS.class);
		arp.addMapping("st_plc_abnormal_i", "rowguid", StPlcAbnormalI.class);
		arp.addMapping("st_rain_s", "rowguid", StRainS.class);
		arp.addMapping("st_rainfull_i", "rowguid", StRainfullI.class);
		arp.addMapping("st_rainrgauge_b", "rowguid", StRainrgaugeB.class);
		arp.addMapping("st_stbprp_b", "rowguid", StStbprpB.class);
		arp.addMapping("st_stgt_b", "rowguid", StStgtB.class);
		arp.addMapping("st_stpp_b", "rowguid", StStppB.class);
		arp.addMapping("st_stsz_b", "rowguid", StStszB.class);
		arp.addMapping("st_vcr_b", "rowguid", StVcrB.class);
		arp.addMapping("st_video_abnormal_i", "rowguid", StVideoAbnormalI.class);
		arp.addMapping("st_water_change_i", "rowguid", StWaterChangeI.class);
		arp.addMapping("st_water_s", "rowguid", StWaterS.class);
		arp.addMapping("st_watergauge_b", "rowguid", StWatergaugeB.class);
		arp.addMapping("sys_account", "id", SysAccount.class);
		arp.addMapping("sys_auth_code", "id", SysAuthCode.class);
		arp.addMapping("sys_menu", "id", SysMenu.class);
		arp.addMapping("sys_session", "id", SysSession.class);
	}
}

