package com.taikesoft.itsm.model;

import com.taikesoft.itsm.model.base.BaseOpAttachment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OpAttachment extends BaseOpAttachment<OpAttachment> {
    public static final OpAttachment dao = new OpAttachment().dao();
    public static final String TABLE = "op_attachment";
}
