package com.taikesoft.itsm.model;

import com.taikesoft.itsm.model.base.BaseOpContent;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OpContent extends BaseOpContent<OpContent> {

    public static final OpContent dao = new OpContent().dao();
    public static final String TABLE = "op_content";
}
