package com.taikesoft.itsm.model;

import com.taikesoft.itsm.model.base.BaseOpIncident;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OpIncident extends BaseOpIncident<OpIncident> {
    public static final OpIncident dao = new OpIncident().dao();
    public static final String TABLE = "op_incident";
}
