package com.taikesoft.itsm.model;

import com.taikesoft.itsm.model.base.BaseOpInspectLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OpInspectLog extends BaseOpInspectLog<OpInspectLog> {
    public static final OpInspectLog dao = new OpInspectLog().dao();
    public static final String TABLE = "op_inspect_log";
}
