package com.taikesoft.itsm.model;

import com.taikesoft.itsm.model.base.BaseOpOtherLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OpOtherLog extends BaseOpOtherLog<OpOtherLog> {
	
}
