package com.taikesoft.itsm.model;

import com.taikesoft.itsm.model.base.BaseOpPlan;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OpPlan extends BaseOpPlan<OpPlan> {
    public static final OpPlan dao = new OpPlan().dao();
    public static final String TABLE = "op_plan";
}
