package com.taikesoft.itsm.model;

import com.taikesoft.itsm.model.base.BaseOpRepairLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OpRepairLog extends BaseOpRepairLog<OpRepairLog> {
	
}
