package com.taikesoft.itsm.model;

import com.taikesoft.itsm.model.base.BaseStInstcdB;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StInstcdB extends BaseStInstcdB<StInstcdB> {
	
}
