package com.taikesoft.itsm.model;

import com.taikesoft.itsm.model.base.BaseStLastwaterS;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StLastwaterS extends BaseStLastwaterS<StLastwaterS> {
	
}
