package com.taikesoft.itsm.model;

import com.taikesoft.itsm.model.base.BaseStPlcAbnormalI;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StPlcAbnormalI extends BaseStPlcAbnormalI<StPlcAbnormalI> {
	
}
