package com.taikesoft.itsm.model;

import com.taikesoft.itsm.model.base.BaseStRainfullI;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StRainfullI extends BaseStRainfullI<StRainfullI> {
	
}
