package com.taikesoft.itsm.model;

import com.taikesoft.itsm.model.base.BaseStRainS;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StRainS extends BaseStRainS<StRainS> {
	
}
