package com.taikesoft.itsm.model;

import com.taikesoft.itsm.model.base.BaseStRainrgaugeB;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StRainrgaugeB extends BaseStRainrgaugeB<StRainrgaugeB> {
	
}
