package com.taikesoft.itsm.model;

import com.taikesoft.itsm.model.base.BaseStStgtB;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StStgtB extends BaseStStgtB<StStgtB> {
	
}
