package com.taikesoft.itsm.model;

import com.taikesoft.itsm.model.base.BaseStStszB;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StStszB extends BaseStStszB<StStszB> {
	
}
