package com.taikesoft.itsm.model;

import com.taikesoft.itsm.model.base.BaseStStbprpB;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StStbprpB extends BaseStStbprpB<StStbprpB> {
	
}
