package com.taikesoft.itsm.model;

import com.taikesoft.itsm.model.base.BaseStStppB;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StStppB extends BaseStStppB<StStppB> {
	
}
