package com.taikesoft.itsm.model;

import com.taikesoft.itsm.model.base.BaseStVideoAbnormalI;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StVideoAbnormalI extends BaseStVideoAbnormalI<StVideoAbnormalI> {
	
}
