package com.taikesoft.itsm.model;

import com.taikesoft.itsm.model.base.BaseStWaterS;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StWaterS extends BaseStWaterS<StWaterS> {
	
}
