package com.taikesoft.itsm.model;

import com.taikesoft.itsm.model.base.BaseStWaterChangeI;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StWaterChangeI extends BaseStWaterChangeI<StWaterChangeI> {
	
}
