package com.taikesoft.itsm.model;

import com.taikesoft.itsm.model.base.BaseStWatergaugeB;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StWatergaugeB extends BaseStWatergaugeB<StWatergaugeB> {
	
}
