package com.taikesoft.itsm.model;

import com.taikesoft.itsm.model.base.BaseSysAccount;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysAccount extends BaseSysAccount<SysAccount> {

    public static final int STATUS_LOCK_ID = -1;	// 锁定账号，无法做任何事情
    public static final int STATUS_OK = 1;			// 正常

    public boolean isStatusOk() {
        return getStatus() == STATUS_OK;
    }

    public boolean isStatusLockId() {
        return getStatus() == STATUS_LOCK_ID;
    }

    public SysAccount removeSensitiveInfo() {
        remove("password", "salt");
        return this;
    }
}
