package com.taikesoft.itsm.model;

import com.taikesoft.itsm.model.base.BaseSysMenu;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysMenu extends BaseSysMenu<SysMenu> {

    public static final SysMenu dao = new SysMenu().dao();
}
